### ISSUE TITLE
Store single unit of temperature

### ISSUE THREAD

**Issue by ot3** [mstenta/atmospi#25]
Please consider the following changes:
1. store either degrees Celsius or Fahrenheit but not both. One can always be algorithmically derived from the other and this way the database is kept smaller and performance is better.
2. add the sqlite command "vacuum" to the instructions, to be executed after upgrading the database. In my case this halved the size of the database.

**Comment by mstenta** [comment]
I thought about only storing Celcius, and then converting to Fahrenheit on-the-fly if that was the selected option, but that would be a huge performance loss to do on-the-fly (much more than simply loading the value).  So I left it alone for now (storing both).

The problem with storing only one is that you can never switch in the future. Granted, maybe that's never going to be necessary.

I'm open to changing this so that it just stores a single value. I haven't had any issues with database size myself, but I suppose much bigger sensor deployments might run into issues. Maybe. I've been running one pi with 4 sensors for over a year (started Jan 17th 2014) gathering readings every 5 minutes, and my log.db is only 15 megabytes.

Similarly, I decided not to include "vacuum" in the instructions because it didn't seem necessary. As the database grows, it will automatically fill in that empty space (and won't grow in size until it reaches that point again).

Do you foresee space being a big issue for you? And if so, can it be solved with a larger SD card?

**Comment by ot3** [comment]
> I thought about only storing Celcius, and then converting to Fahrenheit on-the-fly if that was the  selected option, but that would be a huge performance loss to do on-the-fly (much more than simply loading the value). So I left it alone for now (storing both).

> The problem with storing only one is that you can never switch in the future. Granted, maybe that's never going to be necessary.

OT3: it seems to me that you're either a Celsius or a Fahrenheit person and that in the IMHO rare case that you ever want to switch, this can be done with a script.

> I'm open to changing this so that it just stores a single value. I haven't had any issues with database size myself, but I suppose much bigger sensor deployments might run into issues. Maybe. I've been running one pi with 4 sensors for over a year (started Jan 17th 2014) gathering readings every 5 minutes, and my log.db is only 15 megabytes.

OT3: I'm logging once a minute with currently 10 sensors but haven't yet calculated the database size for a year's worth of data.

> Similarly, I decided not to include "vacuum" in the instructions because it didn't seem necessary. As the database grows, it will automatically fill in that empty space (and won't grow in size until it reaches that point again).

OT3: didn't know that; thanks

Do you foresee space being a big issue for you? And if so, can it be solved with a larger SD card?

**Comment by mstenta** [comment]
I'll change the title of this to "Store single unit of temperature" and we can figure out the details of that...

**Comment by mstenta** [comment]
Dusting off this issue, and reflecting on some of my old comments:

> I thought about only storing Celcius, and then converting to Fahrenheit on-the-fly if that was the selected option, but that would be a huge performance loss to do on-the-fly

I don't remember if I ever did any benchmarking on this, so maybe it's not as big of an issue as I suggested.

Ultimately, the only two sensors Atmospi supports right now are DS18B20 and the DHTxx family - both of which return temperature in Celsius by default. If we only store one value, then it should be whatever the sensor is returning by default.

If we add support for a sensor that returns Fahrenheit by default (doubtful), we may need to make a device setting that specifies C vs F (if we want to store raw values in F).

Storing only Celcius means we could drop the Fahrentheit column entirely.

I may experiment with that if I have some time...

**Comment by mstenta** [comment]
Ok so I made some simple changes: https://github.com/mstenta/atmospi/commit/fa4be832c796fae816c102ad0b5ddc60a1a103a3

- The measure-*.py scripts no longer calculate or save a Fahrenheit reading to the database.
- If you have the `t_unit` setting set to `F`, then it will convert to Fahrenheit when it displays the data in the web UI.

The Fahrenheit column in the Temperature database table is no longer being used, but it is not removed automatically. You do not need to remove it, but if you want to instructions are available here:

https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite
